### DISCUSSION TITLE
Question setting the temperature

### DISCUSSION THREAD

**Discussion by psl2806** [danielrivard/homeassistant-innova#81] [General]
Hi great work. Didn't expect to get this into Home Assistant. BTW I had to install it manually, it  didn't show up in HACS.
I have a question. Is it possible to set the temperature in an automation? 
Thanks!

**Comment by danielrivard** [comment]
Hi, Weird that it would not show up in HACS, I'll verify and make sure it is still in their repo.

As for setting the temperature in an automation, yes, you can use the `Call Service` action with `climate.set_temperature` service, passing the entity name of your unit.

Here is a sample automation:
```yaml
alias: Test
description: ""
trigger: []
condition: []
action:
  - service: climate.set_temperature
    data:
      temperature: 21
    target:
      entity_id: climate.your_innova_entity_name
mode: single
```

Of course, you would fill out your trigger and conditions sections according to your needs.
