### ISSUE TITLE
Can't seem to have more than one unit/entity at a time. 

### ISSUE THREAD

**Issue by GueteBueb** [danielrivard/homeassistant-innova#12]
I've added the integration according to your instructions and  I have been able to add both of my devices but not at the same time.
I did not receive any errors in my logs so far but I also haven't been able to find two separate entities for the devices yet.

Entry in configuration.yaml:

```
climate:
  - platform: innova
    host: 192.168.1.17
    scan_interval: 900
  - platform: innova
    host: 192.168.1.18
    scan_interval: 900
```
