### ISSUE TITLE
Innova HVAC

### ISSUE THREAD

**Issue by putteg** [danielrivard/homeassistant-innova#45]
Hey, I try this intregration but I cant get it to work, My HVAC is a IWZA09NI-1, with wifi and cloud.
I tried without cloud as per your instructions, but it says error all the time, because I prefer without cloud.

Now I tried to add with cloud:
```
climate:
  - platform: innova
    scan_interval: 60
    cloud:
      serial: 2021000707
      uid: xx:yy:zz:aa:bb:xx
```
But still no luck, in log it says.
[(https://pastebin.com/0n3VfvcM)]
