### ISSUE TITLE
Add support for communication through Innova's cloud.

### ISSUE THREAD

**Issue by danielrivard** [danielrivard/homeassistant-innova#5]
Innova does have a way to communicate to the device via its cloud infrastructure. 

It seems to provide a more stable API for the integration and the `scan_interval` could be decreased, but it adds a delay to command completion. 

The [innova-controls](https://github.com/danielrivard/innova-controls) library already supports this method, but the integration does not currently have a way to configure it.

The cloud method needs to have the serial number and the MAC address of the device to identify it when sending API calls.

Ideally, we'd need to find a way to make the local/cloud config mutually exclusive. Or use a config flow, but that would be a different enhancement.

**Comment by danielrivard** [comment]
Preliminary support in branch [cloud-communication](https://github.com/danielrivard/homeassistant-innova/tree/cloud-communication).

It has configuration breaking changes though. 

Cloud config
``` yaml
climate:
  - platform: innova
    scan_interval: 60
    cloud:
      serial: INXXXXXXX
      uid: AB:CD:EF:11:22:33
```
Local config
``` yaml
climate:
  - platform: innova
    scan_interval: 1200
    local:
      host: 192.168.1.100
```
